export const characters= [
        {
            id:0, 
            name:"Harry Potter 0", 
            imgsrc:"hp_foto.png", 
            status:"Vivo", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "gryffindor", 
            isFavorite: false
        },
        {
            id:1, 
            name:"Harry Potter 1", 
            imgsrc:"hp_foto.png", 
            status:"Vivo", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "gryffindor", 
            isFavorite: false
        },
        {
            id:2, 
            name:"Severus Snape", 
            imgsrc:"ss_foto.png", 
            status:"Fallecido", 
            class:"Staff", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"Café Oscuro", 
            hair_color:"Negro", 
            house: "slytherin", 
            isFavorite: true
        },
        {
            id:3, 
            name:"Harry Potter 3", 
            imgsrc:"hp_foto.png", 
            status:"Vivo", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "gryffindor", 
            isFavorite: false
        },
        {
            id:4, 
            name:"Harry Potter 4", 
            imgsrc:"hp_foto.png", 
            status:"Vivo", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "ravenclaw", 
            isFavorite: false
        },
        {
            id:5, 
            name:"Harry Potter 5", 
            imgsrc:"hp_foto.png", 
            status:"Fallecido", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "hufflepuff", 
            isFavorite: false
        },
        {
            id:6, 
            name:"Harry Potter 6", 
            imgsrc:"hp_foto.png", 
            status:"Vivo", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "gryffindor", 
            isFavorite: false
        },
        {
            id:7, 
            name:"Harry Potter 7", 
            imgsrc:"hp_foto.png", 
            status:"Vivo", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "ravenclaw", 
            isFavorite: false
        },
        {
            id:8, 
            name:"Harry Potter 8", 
            imgsrc:"hp_foto.png", 
            status:"Vivo", 
            class:"Estudiante", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "hufflepuff", 
            isFavorite: false
        },
        {
            id:9, 
            name:"Harry Potter 9", 
            imgsrc:"hp_foto.png", 
            status:"Fallecido", 
            class:"Staff", 
            birthday:"31-07-1980", 
            gender:"male", 
            eyes_color:"green", 
            hair_color:"black", 
            house: "slytherin", 
            isFavorite: false
        }
    ];
